# Generated by Django 2.1.3 on 2018-11-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('url', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('comments', models.IntegerField()),
            ],
        ),
    ]
